name: Test Shell Configuration

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run installation script
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Cdaprod/cda.shell-config/main/install.sh)"